---
{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "snappcloud-status-backend.fullname" $ }}
spec:
  host: "status-be.apps.private.{{ .Values.hostname }}"
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: {{ include "snappcloud-status-backend.fullname" $ }}
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
