---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snappcloud-status-backend.fullname" . }}
  labels:
    {{- include "snappcloud-status-backend.labels" . | nindent 4 }}
data:
  configs.yml: | {{- .Values.configs | toYaml | nindent 4 }}

