region: teh-1
hostname: okd4.teh-1.snappcloud.io

configs:
  querier:
    thanos_frontend: "http://thanos-query-frontend-http.openshift-monitoring.svc.cluster.local:9090/api/v1/query"
    services:
      - order: 1
        name: "PaaS"
        queries:
          disruption: '(count(cluster:master_nodes) > 0 and count(cluster:master_nodes) < 3) or (sum(etcd_server_has_leader == 1) > 0 and sum(etcd_server_has_leader == 1) < 3)'
          outage: '(count(cluster:master_nodes) == 0) or (sum(etcd_server_has_leader == 1) == 0)'
      - order: 2
        name: "IaaS"
        queries:
          disruption: '((sum(rate(openstack_cinder_volume_status{status=~"error.*"}[5m]))) and (sum(rate(openstack_nova_server_status{status="UNKNOWN"}[5m])))) > 0'
          outage: '(openstack_cinder_up and openstack_nova_up) == 0'
      - order: 3
        name: "Storage: S3"
        queries:
          disruption: '(sum(rate(radosgw_usage_ops_total[5m])) == 0) and (ceph_health_status == 1)'
          outage: '(sum(rate(radosgw_usage_ops_total[10m])) == 0) and (ceph_health_status == 2)'
      - order: 4
        name: "Service LoadBalancer (L4)"
        queries:
          disruption: 'sum by (name) (increase(health_http_requests_total{status_code!="200",name="svc-lb"}[2m])) / on(name) group_left() sum by (name) (increase(health_http_requests_total{name="svc-lb"}[2m])) * 100 > 2.5'
          outage: 'sum by (name) (increase(health_http_requests_total{status_code!="200",name="svc-lb"}[2m])) / on(name) group_left() sum by (name) (increase(health_http_requests_total{name="svc-lb"}[2m])) * 100 > 10'
      - order: 5
        name: "Ingress (L7)"
        queries:
          disruption: 'sum by (name) (increase(health_http_requests_total{status_code!="200",name=~"(inter-dc|public|private).*"}[2m])) / on(name) group_left() sum by (name) (increase(health_http_requests_total{name=~"(inter-dc|public|private).*"}[2m])) * 100 > 2.5'
          outage: 'sum by (name) (increase(health_http_requests_total{status_code!="200",name=~"(inter-dc|public|private).*"}[2m])) / on(name) group_left() sum by (name) (increase(health_http_requests_total{name=~"(inter-dc|public|private).*"}[2m])) * 100 > 10'
      - order: 6
        name: "Monitoring"
        queries:
          disruption: 'sum(rate(container_cpu_usage_seconds_total{job="kubelet", namespace=~".*-monitoring"}[5m])) > 50 or sum(rate(container_cpu_usage_seconds_total{job="kubelet", namespace=~".*-monitoring"}[5m])) < 30'
          outage: 'up{job=~"monitoring/default"} == 0'
      - order: 7
        name: "Logging"
        queries:
          disruption: 'sum(rate(loki_request_duration_seconds_count{status_code!="200"}[5m])) / sum(rate(loki_request_duration_seconds_count{status_code="200"}[5m])) < 100 and sum(rate(loki_request_duration_seconds_count{status_code!="200"}[5m])) / sum(rate(loki_request_duration_seconds_count{status_code="200"}[5m])) > 350'
          outage: 'sum(rate(loki_request_duration_seconds_count{status_code!="200"}[5m])) / sum(rate(loki_request_duration_seconds_count{status_code="200"}[5m])) < 76 and sum(rate(loki_request_duration_seconds_count{status_code!="200"}[5m])) / sum(rate(loki_request_duration_seconds_count{status_code="200"}[5m])) > 375'
      - order: 8
        name: "Traffic observability: Hubble"
        queries:
          disruption: 'sum(rate(hubble_flows_processed_total[2m])) < 100000'
          outage: 'sum (rate(hubble_flows_processed_total[2m])) < 1000'
      - order: 9
        name: "ArgoCD"
        queries:
          disruption: 'sum(argocd_app_info{health_status="Progressing"}) >= (count(argocd_app_info)/2)'
          outage: 'argocd_cluster_info == 0'
      - order: 10
        name: "Container Registry: Harbor"
        queries:
          disruption: 'rate(image_pulled_total[5m]) < 0.003 and rate(image_pulled_total[5m]) > 0'
          outage: 'rate(image_pulled_total[5m]) == 0'
      - order: 11
        name: "Proxy"
        queries:
          disruption: 'rate(proxy_check_success[5m]) < 0.003 and rate(proxy_check_success[5m]) > 0'
          outage: 'rate(proxy_check_success[5m]) == 0'
