apiVersion: v1
kind: Service
metadata:
  name: {{ include "snappcloud-proxy-client.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "snappcloud-proxy-client.selectorLabels" . | nindent 4 }}
