replicaCount: 1

image:
  repository: ghcr.io/snapp-incubator/snappcloud-status-backend/clients/proxy-client
  pullPolicy: Always
  tag: "0.1.0"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }
podLabels: { }

service:
  type: ClusterIP
  port: 9090

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

configMapName: spcld-proxy-health-client

proxyUrl: proxy.url
