{{- if .Values.httpproxy.enabled -}}
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "snappcloud-status-backend.fullname" $ }}
spec:
  httpVersions:
  - http/1.1
  ingressClassName: private
  routes:
  - enableWebsockets: true
    loadBalancerPolicy:
      strategy: RoundRobin
    services:
    - name: {{ include "snappcloud-status-backend.fullname" . }}
      port: {{ .Values.service.port }}
      weight: 100
    timeoutPolicy:
      idleConnection: 15s
      response: 30s
  virtualhost:
    {{- if .Values.httpproxy.customFQDN }}
    fqdn: {{ .Values.httpproxy.customFQDN }}
    {{- else }}
    fqdn: "status-be.apps.private.{{ .Values.hostname }}"
    {{- end }}
    tls:
      enableFallbackCertificate: true
      secretName: openshift-ingress/letsencrypt
{{- end }}
