replicaCount: 1

image:
  repository: ghcr.io/snapp-incubator/snappcloud-status-backend/clients/harbor-client
  pullPolicy: Always
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

configSecretName: spcld-harbor-health-client
