apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snappcloud-proxy-client.fullname" . }}
  labels:
    {{- include "snappcloud-proxy-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snappcloud-proxy-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snappcloud-proxy-client.selectorLabels" . | nindent 8 }}
      annotations:
        {{- .Values.podAnnotations | toYaml | nindent 8 }}
    spec:
      serviceAccountName: {{ include "snappcloud-proxy-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PROXY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configSecretName }}
                  key: PROXY_URL
          {{ .Values.nodeSelector | toYaml | nindent 8 }}
      tolerations:
        {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      affinity:
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
