name: Build Container Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          for dir in clients/*/; do
          trimmed_dir=${dir::-1} 
            docker buildx build \
              --file $dir/Dockerfile \
              --tag ghcr.io/${{ github.repository }}/$trimmed_dir:latest \
              $dir
            docker push ghcr.io/${{ github.repository }}/$trimmed_dir:latest
          done
