apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snappcloud-harbor-client.fullname" . }}
  labels:
    {{- include "snappcloud-harbor-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snappcloud-harbor-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snappcloud-harbor-client.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: IMAGE_REFERENCE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.configSecretName }}
                  key: IMAGE_REFERENCE
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
