apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "snappcloud-harbor-client.fullname" . }}
  labels:
    {{- include "snappcloud-harbor-client.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "snappcloud-harbor-client.selectorLabels" . | nindent 6 }}
